### ISSUE TITLE
Better Loading Screen for 1.8 crashes on Startup for the new Forge Build 1405

### ISSUE THREAD

**Issue by kreezxil** [AlexIIL/BetterLoadingScreen#22]
[09:48:31] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.minecraft.client.main.Main.main(SourceFile:40) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.client.main.Main.main(SourceFile:40) ~[Main.class:?]
	... 14 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer alexiil.mods.load.coremod.BetterLoadingScreenTransformer@e042c99 from coremod LoadingScreenLoadPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.8-11.14.1.1405-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.client.main.Main.main(SourceFile:40) ~[Main.class:?]
	... 14 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiGameOver
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassWriter.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at alexiil.mods.load.coremod.BetterLoadingScreenTransformer.transformMinecraft(BetterLoadingScreenTransformer.java:117) ~[BetterLoadingScreen-1.8-1.2.8.20.jar:?]
	at alexiil.mods.load.coremod.BetterLoadingScreenTransformer.transform(BetterLoadingScreenTransformer.java:23) ~[BetterLoadingScreen-1.8-1.2.8.20.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.8-11.14.1.1405-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.client.main.Main.main(SourceFile:40) ~[Main.class:?]
	... 14 more

**Comment by AlexIIL** [comment]
Can I have a complete log file please?

**Comment by AlexIIL** [comment]
OK, never mind I have reproduced it.

**Comment by AlexIIL** [comment]
Out of interest, do any of the mods you use (specifically those that contain coremods) work for 1405? I'm not sure how I can fix this, and I'm wondering what other mods don't work (ResourceLoader doesn't for me, so I assume other coremods the change Minecraft.class also won't work)

**Comment by kreezxil** [comment]
Perfect spawn & random things by lumien both no longer work on that build. Which is ironic as lumien contributed to that build.

-----Original Message-----

**Comment by AlexIIL** [comment]
Just preparing a jar file now

**Comment by AlexIIL** [comment]
Turns out I need to rewrite my auto-builder to work properly for older branches, but that will have to wait until tomorrow. Sorry.

**Comment by kreezxil** [comment]
I use 1.8 is it a GO for that?

-----Original Message-----

**Comment by AlexIIL** [comment]
1.3.1 has been pushed to curse forge, waiting for them to approve it.
