### ISSUE TITLE
Configuration screen crashes

### ISSUE THREAD

**Issue by bawr** [AlexIIL/BetterLoadingScreen#29]
Hey, I'm running Better Loading Screen 1.3.5 with Forge 10.13.4.1490.

When I open the configuration screen, the list of contributors and changes loads without a hitch, but pressing the actual "open main configuration" button crashes the game. Welp.

**Comment by bawr** [comment]
The actual error detail is this:
```
java.lang.NullPointerException: Updating screen events

	at alexiil.mods.load.gui.ActualConfig.getConfigElements(ActualConfig.java:25)
	at alexiil.mods.load.gui.ActualConfig.<init>(ActualConfig.java:18)
	at alexiil.mods.load.gui.BaseConfig.func_146284_a(BaseConfig.java:141)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by AlexIIL** [comment]
1.7.10?

**Comment by AlexIIL** [comment]
Ok, nvm, I didn't think that was in the 1.7.10 version. Looking at it now.

**Comment by bawr** [comment]
Eyup, it's 1.7.10 over here.

**Comment by AlexIIL** [comment]
Well, that was a rather nice 1 line fix :)

**Comment by AlexIIL** [comment]
I'll push a version out soon.

**Comment by bawr** [comment]
Awesome!

Although I already read enough code to write my config file by hand. All the same, if you could push it to Github before Curse that'd be appreciated, the latter tends to lag with updates, I hate having those "break my game" buttons. ;)

**Comment by AlexIIL** [comment]
I'm uploading it to curse now, hopefully it won't crash and burn and die :)

Oh, and i'll have to add another way to make people crash when they dare use a helpful button :)










(sarcasm)

**Comment by bawr** [comment]
Confirmed as working. :)

The wiki could use a note on the different position types, though, I had to search the github repo to get my bottom-aligned text goodness.

**Comment by AlexIIL** [comment]
Good point. The entirety of the config needs properly explaining, but it doesn't help that i'm completely changing the way it works for 1.4.x :)
