### ISSUE TITLE
crash with LiteLoader

### ISSUE THREAD

**Issue by BlayzerQ** [AlexIIL/BetterLoadingScreen#47]
Last version liteloader and CustomLoadingScreen.

java.lang.IllegalStateException: Cannot go to state <INIT> as <BEGINGAME> is [ACTIVE] but [INCOMPLETE] 
	at com.mumfrey.liteloader.launch.LiteLoaderTweaker$StartupState.gotoState(LiteLoaderTweaker.java:334)
	at com.mumfrey.liteloader.launch.LiteLoaderTweaker.onInit(LiteLoaderTweaker.java:121)
	at com.mumfrey.liteloader.launch.LiteLoaderTweaker.init(LiteLoaderTweaker.java:296)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at launcher.client.ClientLauncher.launch(ClientLauncher.java:285)
	at launcher.client.ClientLauncher.main(ClientLauncher.java:186)
Caused by: java.lang.Throwable: java.lang.NoClassDefFoundError: alexiil/mods/load/LiteLoaderProgress
	at com.mumfrey.liteloader.client.api.ObjectFactoryClient.preBeginGame(ObjectFactoryClient.java)
	at com.mumfrey.liteloader.core.LiteLoaderBootstrap.preBeginGame(LiteLoaderBootstrap.java:192)
	at com.mumfrey.liteloader.launch.LiteLoaderTweaker.onPreBeginGame(LiteLoaderTweaker.java:112)
	at com.mumfrey.liteloader.launch.LiteLoaderTweaker.preBeginGame(LiteLoaderTweaker.java:292)
	at net.minecraft.client.main.Main.main(SourceFile)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at launcher.client.ClientLauncher.launch(ClientLauncher.java:285)
	at launcher.client.ClientLauncher.main(ClientLauncher.java:186)
Caused by: java.lang.ClassNotFoundException: alexiil.mods.load.LiteLoaderProgress
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:197)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: com/mumfrey/liteloader/client/gui/startup/LoadingBar
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
	... 19 more
Caused by: java.lang.ClassNotFoundException: com.mumfrey.liteloader.client.gui.startup.LoadingBar
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

	at com.mumfrey.liteloader.util.log.LiteLoaderLogger.getLastThrowable(LiteLoaderLogger.java:94)
	... 18 more

**Comment by AlexIIL** [comment]
What exact versions of custom loading screen and liteloader are you using? (and also what minecraft versions)

**Comment by BlayzerQ** [comment]
BetterLoadingScreen-1.3.9
liteloader-1.7.10-04
MC 1.7.10

**Comment by AlexIIL** [comment]
Thanks, I'll look into it. However I can't promise anything soon so you might want to try disabling liteloader's loading screen manually, or removing CLS (I don't have a config option for disabling the coremod)
