### ISSUE TITLE
Crash of 1.7.10-1.3.10 when trying to load resource loader compat

### ISSUE THREAD

**Issue by MajorTuvok** [AlexIIL/BetterLoadingScreen#49]
Hello,
As I was trying to find an Error with an Friends server, which prevented it from starting, I noticed that your mod threw an ClassNotFoundException:
````
[10:54:13] [Server thread/INFO] [STDOUT/betterloadingscreen]: [alexiil.mods.load.coremod.BetterLoadingScreenTransformer:transformResourceLoader:142]: Transformed ResourceLoader!
[10:54:13] [Server thread/INFO] [STDOUT/betterloadingscreen]: [alexiil.mods.load.ProgressDisplayer:loadResourceLoader:108]: Resource Loader Compat FAILED!
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at alexiil.mods.load.ProgressDisplayer.loadResourceLoader(ProgressDisplayer.java:101)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at alexiil.mods.load.ProgressDisplayer.displayProgress(ProgressDisplayer.java:172)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at alexiil.mods.load.ModLoadingListener.doProgress(ModLoadingListener.java:151)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at alexiil.mods.load.BetterLoadingScreen.construct(BetterLoadingScreen.java:73)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: lumien/resourceloader/loader/NormalResourceLoader
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at lumien.resourceloader.ResourceLoader.preInit(ResourceLoader.java:29)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 39 more
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: lumien.resourceloader.loader.NormalResourceLoader
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 40 more
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/IResourcePack
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 42 more
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.IResourcePack
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 46 more
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 48 more
[10:54:13] [Server thread/INFO] [STDOUT/betterloadingscreen]: [alexiil.mods.load.ProgressDisplayer:overrideForgeSplashProgress:212]: Could not override forge's splash screen for some reason...
[10:54:13] [Server thread/INFO] [STDOUT/betterloadingscreen]: [alexiil.mods.load.ProgressDisplayer:overrideForgeSplashProgress:213]: class = null
[10:54:13] [Server thread/INFO] [STDOUT/betterloadingscreen]: [alexiil.mods.load.ProgressDisplayer:overrideForgeSplashProgress:214]: field = null
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: net/minecraft/client/resources/IResourcePack
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName0(Native Method)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName(Class.java:264)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at alexiil.mods.load.ProgressDisplayer.overrideForgeSplashProgress(ProgressDisplayer.java:202)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at alexiil.mods.load.ProgressDisplayer.displayProgress(ProgressDisplayer.java:173)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at alexiil.mods.load.ModLoadingListener.doProgress(ModLoadingListener.java:151)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at alexiil.mods.load.BetterLoadingScreen.construct(BetterLoadingScreen.java:73)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.IResourcePack
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:54:13] [Server thread/INFO] [STDERR/betterloadingscreen]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 37 more
````
PS: I don't known much about this Mod, but as far as I can tell this is a client-only mod, right?
So Maybe you could drop Server support (f.e. check physical sides, so that nothing is done at all on the Server) preventing people like my friend from trying this mod on a server.

**Comment by MajorTuvok** [comment]
Apperently this Error doesn't seem to be caused by your mod, but only propagated. Because quite the underlying ClassNotFound was thrown by the mod resource Loader mod itself (I removed your mod from the server and then, finally, ResourceLoader came to the conclusion it should throw it's own exceptions itself). I would still recommend that you try to catch Reflection caused Exceptions as this may result in other Problems, although I will close this issue anyway as it's main problem lays with ResourceLoader and not this mod.

**Comment by AlexIIL** [comment]
...right, i completely forgot about that bit - CustomLoadingScreen can display a server boot status in a separate window if "useMinecraft" is set to false. I'm not sure how useful it I should however.

And this definitely makes this *my* fault, rather than ResourceLoaders

**Comment by MajorTuvok** [comment]
Ah ok
