### ISSUE TITLE
strange crash

### ISSUE THREAD

**Issue by Exzept1on** [AlexIIL/BetterLoadingScreen#72]
Hi :D
[crash-2021-08-07_05.33.11-client.txt](https://github.com/AlexIIL/CustomLoadingScreen/files/6948314/crash-2021-08-07_05.33.11-client.txt)

A strange crash of minecraft, which is not connected with anything. The crash appears two or three times a week. I can't understand why, but I can attach a crash log.

**Comment by edgaradr223** [comment]
hey mate, did yoyu managed to fix this? im having the exact same crashes

Stacktrace:
	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:601)
	at net.minecraftforge.fml.client.SplashProgress.pause(SplashProgress.java:614)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by AlexIIL** [comment]
Oh, sorry - not yet.

**Comment by AlexIIL** [comment]
@edgaradr223 Can you upload a full log? That's either not the same issue as this one is, or that doesn't contain any more information to identify it as such.

**Comment by edgaradr223** [comment]
[crash-2021-10-09_15.04.41-client.txt](https://github.com/AlexIIL/CustomLoadingScreen/files/7316454/crash-2021-10-09_15.04.41-client.txt)

Of course

**Comment by AlexIIL** [comment]
Thanks! Sorry, it is - I just wanted to make sure. (The important part is below)
````
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:373)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:327)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110990_a(TextureUtil.java:314)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:266)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:246)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:206)
	at alexiil.mc.mod.load.render.TextureLoader$1.func_110551_a(TextureLoader.java:112)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:90)
````

**Comment by AlexIIL** [comment]
This should be fixed in [1.5.6](https://www.curseforge.com/minecraft/mc-mods/better-loading-screen/files/3486258), can you test it to make sure?

**Comment by edgaradr223** [comment]
tested new version, i tried with both config/slideshow and sample/slideshow, you can see my config file here:
 
![image](https://user-images.githubusercontent.com/50599044/136677432-e3c4134e-6327-492d-9c9c-d226c4b2d190.png)

you can see my config/customloadingscreen/ directory here:

![image](https://user-images.githubusercontent.com/50599044/136677458-b8fd9e9e-0b31-4983-b106-ec2d0047ed7b.png)

both configurations sample/slideshow and config/slideshow are throwing this screen:


![image](https://user-images.githubusercontent.com/50599044/136677400-881db276-b814-4ccd-92d9-40ef4b81cacd.png)

thats weird right

**Comment by AlexIIL** [comment]
@edgaradr223 Ah sorry - I mean could you test to see if you get the crash from this issue - that comment would be better suited to https://github.com/AlexIIL/CustomLoadingScreen/issues/73

**Comment by edgaradr223** [comment]
oh okay, apparently im not getting the error, opened/closed minecraft around 9 times

**Comment by Exzept1on** [comment]
Have you fixed this issue? I will also test the new version today.

**Comment by AlexIIL** [comment]
Yes - 1.5.6 should have fixed this crash. Please do! That way I know we can close this issue :)

**Comment by Exzept1on** [comment]
[crash-2021-10-11_15.21.44-client.txt](https://github.com/AlexIIL/CustomLoadingScreen/files/7321228/crash-2021-10-11_15.21.44-client.txt)
Hmm

**Comment by Exzept1on** [comment]
![image](https://user-images.githubusercontent.com/52341158/136766703-58f53deb-9f9f-4e70-98a3-cf1db6919f79.png)
Also, after installing 1.5.6, I had the same error.
But I tried 1.5.7-pre1 which is described in error #73, and everything worked,

**Comment by edgaradr223** [comment]
> ![image](https://user-images.githubusercontent.com/52341158/136766703-58f53deb-9f9f-4e70-98a3-cf1db6919f79.png) Also, after installing 1.5.6, I had the same error. But I tried 1.5.7-pre1 which is described in error #73, and everything worked,

https://alexiil.uk/mods/CustomLoadingScreen/CustomLoadingScreen-1.12.2-1.5.7-pre.1.jar

Try that version bro, is error proof

**Comment by AlexIIL** [comment]
> From @SpeeeDCraft 
> crash-2021-10-11_15.21.44-client.txt
> Hmm

That's actually a different error, which happens to be the same one as #73 - hence why the fix worked :)

> From @edgaradr223 
> Try that version bro, is error proof

He did :p

**Comment by Exzept1on** [comment]
Then thank you very much. I'm waiting for version 1.5.7 on curseforge. :з
